;; Minimal byte-stable component for the pinned-digest verify path: the
;; sibling module.toml pins this file's exact sha256, so the pair stays
;; green in CI without any per-machine wasm build. Do not edit this file
;; without re-pinning the digest (sha256sum component.wat).
(component)
